### ISSUE TITLE
Large margin in the bottom of scrollviewer

### ISSUE THREAD

**Issue by soundprojects** [brofrain/leptos-animated-for#4]
I have about 100 item components in an AnimatedFor loop but when I scroll to the bottom of my scrollviewer, there is space left for about 8 more items. There are no other elements there and there are no bottom margins set as far as I can see.

Is there anywhere I can look to provide you with more information?

**Comment by brofrain** [comment]
I can speculate that maybe some zombie elements were made invisible via leave transition and not removed afterward. But I need a reproducible example for investigating the real cause and whether it should be fixed.
